url:
title: Lart的个人WIKI
keywords: 机器学习, 深度学习, 技术
description: 看到的, 用到的.
author: Lart2P

root: /
source: content
destination: output
themes_dir: themes
theme: simple2

default_ext: md
pygments: true
debug: false
